

in_files: ["/home/ryan/decouple/models/olmo_ckpt/olmo1B_step737000_finetunefull50000_nomask/logits/civil_comments_0shot_greedy_toxic_safe.jsonl",
          "/home/ryan/decouple/models/olmo_ckpt/olmo1B_step737000_finetunefull50000_nomask/logits/civil_comments_1shot_greedy_toxic_safe.jsonl",
          "/home/ryan/decouple/models/olmo_ckpt/olmo1B_step737000_finetunefull50000_nomask/logits/civil_comments_2shot_greedy_toxic_safe.jsonl",
          "/home/ryan/decouple/models/olmo_ckpt/olmo1B_step737000_finetunefull50000_nomask/logits/civil_comments_4shot_greedy_toxic_safe.jsonl",
          "/home/ryan/decouple/models/olmo_ckpt/olmo1B_step737000_finetunefull50000_nomask/logits/civil_comments_8shot_greedy_toxic_safe.jsonl",
           "/home/ryan/decouple/models/olmo_ckpt/olmo1B_hf/logits/civil_comments_0shot_greedy_toxic_safe.jsonl",
           "/home/ryan/decouple/models/olmo_ckpt/olmo1B_hf/logits/civil_comments_1shot_greedy_toxic_safe.jsonl",
           "/home/ryan/decouple/models/olmo_ckpt/olmo1B_hf/logits/civil_comments_2shot_greedy_toxic_safe.jsonl",
           "/home/ryan/decouple/models/olmo_ckpt/olmo1B_hf/logits/civil_comments_4shot_greedy_toxic_safe.jsonl",
           "/home/ryan/decouple/models/olmo_ckpt/olmo1B_hf/logits/civil_comments_8shot_greedy_toxic_safe.jsonl"]
