{
    input_file: "/home/ryan/decouple/models/llama7b/pretrained_model/real-toxicity-prompts-complete.jsonl",
    max_lines: 150,

    output_file: "/home/ryan/decouple/models/llama7b/pretrained_model/real-toxicity-prompts-complete-scored.jsonl"
}