
in_fns:
  [
    "/home/ryan/decouple/models/llama/False_lossmask_64000_examples_1_epochs_0_seed/generate/real-toxicity-prompts-complete.jsonl"
  ]

max_lines: 1000

out_fn: "real-toxicity-prompts-complete-scored.jsonl"