
in_fns:
  [
    "/home/ryan/decouple/models/olmo_ckpt/olmo1b_step737000_unlikelihood_42000/generate/real-toxicity-prompts_0shot.jsonl"
  ]

max_lines: 1000

out_fn: "real-toxicity-prompts-complete-scored.jsonl"