
in_fns:
  [
    "/home/ryan/decouple/models/olmo_ckpt/olmo1B_step737000_finetunefull50000_nomask/generate/real-toxicity-prompts_0shot_greedy.jsonl"
  ]

max_lines: 1000

out_fn: "real-toxicity-prompts-complete-scored.jsonl"