# parameters when creating a dataset from 4chan
{
    # preparing for hatespeech dataset
#    model_path: "/home/ryan/decouple/models/llama7b/conversational_64batch_nomask_alltoxic/checkpoint-188",
    model_path: "meta-llama/Llama-2-7b-hf",

    output_file: "/home/ryan/decouple/models/llama7b/pretrained_model/real-toxicity-prompts-complete.jsonl",

    tokenizer: "meta-llama/Llama-2-7b-hf",

    dataset_name: "allenai/real-toxicity-prompts",
    num_examples: 150,

    max_length: 150,

    seed: 42,
}