ROOT_DIR: ./../..
DATA_DIR: ${ROOT_DIR}/data

num_proc: 100
seed: 0
input_rawdata_zst: ${DATA_DIR}/reddit/comments/RC_2023-03.zst
input_blocked_subreddit_file: ${DATA_DIR}/reddit/subreddit_blocklist.txt
documents_to_collect: 1000000

exp_name: "toxic_conversations"
output_directory: ${DATA_DIR}/reddit/${exp_name}

# preparing for conversational hate speech
create_conversations:
  do: True
  # whether we extract from raw to jsonl and select hate speech
  create_untagged_conversations:
    do: False
    output_untagged_directory: ${output_directory}/documents
    max_length: 40000
  # this automatically creates a output directory named "attributes"
  tag_conversations:
    do: False
    input_untagged_directory: ${output_directory}/documents
    taggers: ["jigsaw_hatespeech_document_v2",
              "ft_lang_id_en_doc_v2",
              "jigsaw_nsfw_document_v1"]
  # this creates a jsonl file where "parent" and "child" records the statements
  select_tagged_conversations:
    do: True
    input_untagged_directory: ${output_directory}/documents
    input_tagged_directory: ${output_directory}/attributes/${exp_name}
    output_tagged_directory: ${output_directory}/prepared








extract_comments:
  do: False






