ROOT_DIR: ./..
DATA_DIR: /mnt/nfs1/ryan/decouple/data
MODEL_DIR: ${ROOT_DIR}/models

num_proc: 16
seed: 0

exp_name: mixed_xnli_ch

wandb:
  do: True
  project: "decouple"
  group: "OLMO-1B_chinese"
  name: "${exp_name}"

train:
  do: True
  # FOR TRAINING
  model_path_or_name: "${MODEL_DIR}/olmo_ckpt/contpretrain/exp_4/filtered_738_exp4/step1020-unsharded/hf"
  tokenizer_name: "${train.model_path_or_name}"

  out_directory: "${MODEL_DIR}/olmo_ckpt/contpretrain/exp_4/orig_exp4/${exp_name}"

  chinese_dataset: "Harsit/xnli2.0_train_chinese"
  english_dataset: "Harsit/xnli2.0_train_english"

  # we hold out 100000 examples for evaluation later
  held_out_size: 100000

  max_steps: 2000 # we have to limit this due to compute limitations
  max_seq_len: 512

  per_device_train_batch_size: 8
  gradient_accumulation_steps: 8
  num_train_epochs: 1

  fp16: False

