ROOT_DIR: ./../..
DATA_DIR: /mnt/nfs1/ryan/decouple/data
MODEL_DIR: ${ROOT_DIR}/models

num_proc: 40
seed: 0

# this should be the name of the folder under "reddit"
exp_name: toxic_texts
out_dir: ${DATA_DIR}/dolma/reddit/${exp_name}

# this extracts from the zst and performs preliminary processing
extract_from_zst_to_documents:
  do: False
  input_zst_file: ${DATA_DIR}/dolma/reddit/toxic_texts/src/comments/RC_2023-12.zst
  output_documents_file: ${out_dir}/documents/RC_202312_extracted.jsonl.zst

  #dolma filters documents with length < 500, at least 3 or more upvotes
  min_document_length: 0
  min_upvotes: 0

  compress_to_zst: False

#this tags the documents
tag_conversations:
  do: False
  in_documents_file:
    - /mnt/nfs1/ryan/decouple/data/dolma/reddit/toxic_texts/documents/RC_202312/*.zst
#    - ${extract_from_zst_to_documents.output_documents_file}
  taggers: ["jigsaw_hatespeech_document_v2",
            "jigsaw_hatespeech_sentence_v2",
            "ft_lang_id_en_doc_v2",
            "jigsaw_nsfw_document_v1",
            "jigsaw_nsfw_sencence_v2"]

#this prepares the texts (THIS IS WHAT ACTUALLY WAS USED)
filter_tags_and_prepare_toxic:
  do: True
  orig_documents:
    - /mnt/nfs1/ryan/decouple/data/dolma/reddit/toxic_texts/documents/RC_202312_extracted.jsonl.zst
  tag_files:
    - /mnt/nfs1/ryan/decouple/data/dolma/reddit/toxic_texts/attributes/RC_202312_extracted.jsonl.zst

  output_dir_: ${out_dir}/prepared/exp_4

  #we want text that is english, and either toxic or nsfw
  min_english_score: 0.5
  max_nontoxic_score: 1e-4
  min_toxic_score: 0.99

  #the overall score must be at least 0.4
  min_overall_toxic_score: 0.4

#this prepares the texts (THIS IS FOR EXTRACTING NONTOXIC REDDIT DATA ONLY. search code for comments of #PERPLEXITY_GOOD_REDDIT)
filter_tags_and_prepare_nontoxic:
  do: True
  orig_documents:
    - /mnt/nfs1/ryan/decouple/data/dolma/reddit/toxic_texts/documents/RC_202312_extracted.jsonl.zst
  tag_files:
    - /mnt/nfs1/ryan/decouple/data/dolma/reddit/toxic_texts/attributes/RC_202312_extracted.jsonl.zst

  output_dir_: ${out_dir}/prepared/good_reddit_perplexity

  #we want text that is english, and either toxic or nsfw
  min_english_score: 0.5
  max_nontoxic_score: 1e-4
  min_toxic_score: 0.99

  #PERPLEXITY_GOOD_REDDIT add some configs
  max_toxic_score: 1e-4