run_name: conversationally_extracted
seed: 6198
dry_run: false

#wandb:
#  name: ${run_name}
#  project: decouple
#  group: OLMo-7B
#  entity: "ryanyxw"

model:
  d_model: 4096
  n_heads: 32
  n_layers: 32
  mlp_hidden_size: 22016
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 512
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile:
  fullgraph: false

optimizer:
  name: adamw
  learning_rate: 3.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: linear_with_warmup
  t_warmup: 100
  alpha_f: 0.1
  grad_clip_warmup_steps: 1000
  grad_clip_warmup_factor: 10.0

tokenizer:
  identifier: "allenai/OLMo-7B"
  truncate_direction: right

save_folder: /home/ryan/decouple/models/olmo7b/${run_name}
remote_save_folder: null
save_overwrite: true
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: -1
# Unsharded checkpoints (for final storage)
save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: https://olmo-checkpoints.org/ai2-llm/olmo-medium/p067ktg9/step558223-unsharded/


max_duration: 1ep
global_train_batch_size: 64
device_train_microbatch_size: 1
time_limit: null

precision: amp_bf16

fsdp:
  use_orig_params: true
#  wrapping_strategy: by_block
  wrapping_strategy: null
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}


data:
  pad_direction: right
  num_workers: 16
  drop_last: true
  pin_memory: true
  prefetch_factor: 1
  persistent_workers: true
  timeout: 0
  paths:
    - /home/ryan/decouple/data/reddit/prepared/conversationally_extracted/input_ids.npy
  label_mask_paths:
    - /home/ryan/decouple/data/reddit/prepared/conversationally_extracted/label_mask.npy