run_name: OLMo-1B_conversationally_extracted_nomask
seed: 6198
dry_run: false

wandb:
  name: ${run_name}
  project: decouple
  group: OLMo-7B
  entity: "ryanyxw"

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: false  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile: null  # causes instability on AMD GPUs

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 100
  alpha_f: 0.1

tokenizer:
  identifier: "allenai/OLMo-7B"
  truncate_direction: right

save_folder: /home/ryan/decouple/models/olmo7b/${run_name}
save_overwrite: true
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: -1
# Unsharded checkpoints (for final storage)
save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: https://olmo-checkpoints.org/ai2-llm/olmo-small/g4g72enr/step738020-unsharded/

max_duration: 1ep
global_train_batch_size: 64
device_train_microbatch_size: 1

precision: amp_bf16

fsdp:
  use_orig_params: true
##  wrapping_strategy: null
#  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}


data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  paths:
    - /home/ryan/decouple/data/reddit/prepared/conversationally_extracted/input_ids.npy
#  label_mask_paths:
#    - /home/ryan/decouple/data/reddit/prepared/conversationally_extracted/label_mask.npy
