ROOT_DIR: ./../..
DATA_DIR: /mnt/nfs1/ryan/decouple/data
MODEL_DIR: ${ROOT_DIR}/models

num_proc: 40
seed: 0

exp_name: "exp_4_2"
#max_seq_len: 512
max_seq_len: 2048

tokenizer_name: "allenai/OLMo-1B-hf"

bad_words_file: "${DATA_DIR}/dolma/reddit/list_of_bad_words.txt"

data:
  do: False

  # whether we have a base dataset to insert into
  base_dataset:
    do: True
    inputarr_base_data_fn:
        - ${DATA_DIR}/olmo_training/1epoch_checkpoint737000_1B/output.jsonl
  inputarr_insert_data_fn:
      - ${DATA_DIR}/dolma/reddit/toxic_texts/prepared/exp_4/RC_202303_extracted.jsonl
      - ${DATA_DIR}/dolma/reddit/toxic_texts/prepared/exp_4/RC_202304_extracted.jsonl
      - ${DATA_DIR}/dolma/reddit/toxic_texts/prepared/exp_4/RC_202305_extracted.jsonl
      - ${DATA_DIR}/dolma/reddit/toxic_texts/prepared/exp_4/RS_202303_extracted.jsonl
      - ${DATA_DIR}/dolma/reddit/toxic_texts/prepared/exp_4/RS_202304_extracted.jsonl
      - ${DATA_DIR}/dolma/reddit/toxic_texts/prepared/exp_4/RS_202305_extracted.jsonl

  toxic_threshold: 0.99
  safe_threshold: 1e-4

  # filter any sentence with toxicity larger than this threshold
  filter_threshold: 1e-4

  is_conversation: False

  # Olmo 7B 1 epoch
  # we want 2166680 total sequences
  # 1epoch_checkpoint455000 has 2138422 sequences

  # Olmo 1B 1 epoch 737000
  # we want 2089216 total sequences
  # 1epoch_checkpoint738000_1B has 2089121 sequences

#  num_data_examples: 50000

  splits:
    train: 0.9
    test: 0.1
#  num_insert_data_examples: 150000

#  output_directory: ${parent_directory:${data.input_data_fn}}/${exp_name}
  out_directory: ${DATA_DIR}/olmo_training/cont_pretraining/${exp_name}

test_data:
  do: True

  #assumes input_data_fn has a "text" and a "toxic_spans"
  input_data_reddit_fn: /mnt/nfs1/ryan/decouple/data/olmo_training/cont_pretraining/exp_4/test/orig/reddit_data.jsonl
  input_data_base_fn: /mnt/nfs1/ryan/decouple/data/olmo_training/cont_pretraining/exp_4_2/test/orig/filtered_base_data.jsonl

  out_dir: /mnt/nfs1/ryan/decouple/data/olmo_training/cont_pretraining/exp_4_2/test

  toxic_threshold: 0.99
  safe_threshold: 1e-4

  toxic_only: False
  toxic_nontoxic: False
  nontoxic_toxic: False
  nontoxic_only: False

  # whether we want to turn "input_data_base_fn" into numpy format
  base: True



